export const SEARCH_NEWS_REQUEST = "SEARCH_SKILLS_REQUEST";
export const SEARCH_NEWS_FAILURE = "SEARCH_SKILLS_FAILURE";
export const SEARCH_NEWS_SUCCESS = "SEARCH_SKILLS_SUCCESS";
// export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";
// export const CHANGE_RESET_STORE = "CHANGE_RESET_STORE";
